"""Build data/schema_filtered_full.sql: the full DDL minus tables that are
completely empty (0 rows) in data/erp_legacy.db. Keeps the file usable as
context for a model without wasting tokens on ~1,096 structurally-empty
noise tables (see context.md section 7)."""
import re
import sqlite3

DB_PATH = "data/erp_legacy.db"
FULL_SCHEMA_PATH = "data/schema_full.sql"
OUT_PATH = "data/schema_filtered_full.sql"

con = sqlite3.connect(DB_PATH)
cur = con.cursor()
tables = [r[0] for r in cur.execute("SELECT name FROM sqlite_master WHERE type='table'")]
row_counts = {}
for t in tables:
    try:
        row_counts[t] = cur.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
    except sqlite3.Error:
        row_counts[t] = -1  # unknown, keep it to be safe
con.close()

with open(FULL_SCHEMA_PATH, encoding="utf-8") as fh:
    text = fh.read()

# Split into: leading header/comments, then one chunk per "CREATE TABLE ...".
starts = [m.start() for m in re.finditer(r"CREATE TABLE", text)]
header = text[: starts[0]] if starts else text
chunks = []
for i, start in enumerate(starts):
    end = starts[i + 1] if i + 1 < len(starts) else len(text)
    chunks.append(text[start:end])

name_re = re.compile(r"CREATE TABLE\s+(\w+)\s*\(")

kept, dropped = [], []
for chunk in chunks:
    m = name_re.match(chunk)
    if not m:
        kept.append(chunk)  # unrecognized shape, keep to be safe
        continue
    name = m.group(1)
    count = row_counts.get(name, -1)
    if count == 0:
        dropped.append(name)
    else:
        kept.append(chunk)

new_header = (
    "-- Filtered DDL export, client 800, system PRD\n"
    f"-- Derived from schema_full.sql ({len(chunks)} tables total).\n"
    f"-- {len(dropped)} tables with 0 rows in data/erp_legacy.db have been removed\n"
    "-- to avoid wasting model context on structurally-empty noise tables.\n"
    f"-- {len(kept)} tables remain (14 core P2P tables + all other populated tables).\n"
    "-- See context.md section 7 for how table trustworthiness was established -\n"
    "-- a populated table below is not automatically meaningful or joinable to\n"
    "-- the core P2P entities; many are synthetic filler with non-matching keys.\n"
    "-- Generated by build_filtered_schema.py. Do not edit by hand.\n\n"
)

with open(OUT_PATH, "w", encoding="utf-8") as fh:
    fh.write(new_header)
    fh.write("".join(kept))

print(f"total tables: {len(chunks)}")
print(f"dropped (0 rows): {len(dropped)}")
print(f"kept: {len(kept)}")
